on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Build and release
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          project_path: ./cmd/cardamon
          md5sum: true
          sha256sum: true
